name: Generate Trophies

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: |
          git clone --depth 1 https://github.com/ryo-ma/github-profile-trophy.git /tmp/trophy
          cd /tmp/trophy
          deno run --allow-net --allow-env --allow-read --allow-write ./render_svg.ts ericAleixo /tmp/output algolia
          mkdir -p $GITHUB_WORKSPACE/assets
          cp /tmp/output/*.svg $GITHUB_WORKSPACE/assets/trophy.svg
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update trophy svg"